version: 2.1
jobs:
  cylonAPI:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: 
         name: "Cylon service run"
         command: | 
              go run cylonAPI.go t pid img env -o > cylonresponse.json
              cat cylonresponse.json 
 
workflows:
  Cylon API Response:
    jobs:
      - cylonAPI
      